import {
  BedrockAgentRuntimeClient,
  RetrieveCommand,
} from "@aws-sdk/client-bedrock-agent-runtime";

import {
  BedrockRuntimeClient,
  ConverseCommand,
} from "@aws-sdk/client-bedrock-runtime";


const region = process.env.AWS_REGION;

const knowledgeBaseClient =
  new BedrockAgentRuntimeClient({
    region,
  });

const modelClient =
  new BedrockRuntimeClient({
    region,
  });


  const KB_ID = process.env.KB_ID;
  const MODEL_ID = process.env.MODEL_ID;
  
  const GUARDRAIL_ID =
    process.env.GUARDRAIL_ID;
  
  const GUARDRAIL_VERSION =
    process.env.GUARDRAIL_VERSION;


/*
  Map our S3 source files back to the original
  official Singapore Courts URLs.

  This lets the frontend show useful clickable
  citations instead of s3:// links.
*/
const SOURCE_URLS = {
  "how-to-file-serve-small-claim.md":
    "https://www.judiciary.gov.sg/civil/how-to-file-serve-small-claim",

  "cases-eligible-small-claim.md":
    "https://www.judiciary.gov.sg/civil/cases-eligible-small-claim/1000",

  "understand-outcomes-small-claim.md":
    "https://www.judiciary.gov.sg/civil/understand-outcomes-small-claim",

  "before-going-to-court-small-claim.md":
    "https://www.judiciary.gov.sg/civil/before-going-to-court-small-claim",

  "at-small-claims-consultation.md":
    "https://www.judiciary.gov.sg/civil/at-small-claims-consultation",

  "at-small-claims-hearing.md":
    "https://www.judiciary.gov.sg/civil/at-small-claims-hearing",

  "court-users-generative-ai-guide.pdf":
    "https://www.judiciary.gov.sg/docs/default-source/news-and-resources-docs/guide-on-the-use-of-generative-ai-tools-by-court-users.pdf",

  "sct-ai-generated-summaries-guide.pdf":
    "https://www.judiciary.gov.sg/docs/default-source/civil-docs/guide-to-sct-ai-generated-summaries.pdf",
};


function getFileName(uri = "") {
  const parts = uri.split("/");
  return decodeURIComponent(
    parts[parts.length - 1] || "Official source"
  );
}


function corsHeaders() {
  return {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
  };
}

function detectLegalAdviceIntent(question = "") {
  const text = question
    .toLowerCase()
    .trim();

  const patterns = [
    /\bwill i win\b/i,
    /\bcan i win\b/i,
    /\bdo i have a strong case\b/i,
    /\bchances? of winning\b/i,
    /\blikely to win\b/i,

    /\bwhat argument should i\b/i,
    /\bwhat should i argue\b/i,
    /\bhow should i argue\b/i,
    /\bbest argument\b/i,
    /\bstrategy\b/i,
    /\bmaximi[sz]e my chances\b/i,

    /\bshould i settle\b/i,
    /\bshould i accept\b/i,
    /\bshould i go to (a )?hearing\b/i,
    /\bshould i sue\b/i,

    /\bwhat should i do legally\b/i,
    /\btell me exactly what i should do\b/i,
    /\bwhat legal action should i take\b/i,
  ];

  return patterns.some(
    (pattern) => pattern.test(text)
  );
}

function buildRetrievalQuery(question) {
  const lowerQuestion = question.toLowerCase();

  const isAiQuestion =
    /\bai\b/i.test(question) ||
    lowerQuestion.includes("chatgpt") ||
    lowerQuestion.includes("generative ai") ||
    lowerQuestion.includes("genai") ||
    lowerQuestion.includes("artificial intelligence") ||
    /\bllm\b/i.test(question) ||
    lowerQuestion.includes("hallucination") ||
    lowerQuestion.includes("ai-generated");

  if (isAiQuestion) {
    return `
${question}

Relevant official guidance may concern:
Generative AI tools,
self-represented persons,
court users,
Court Documents,
fact-checking,
independent verification,
accuracy,
hallucinations,
legal advice,
and responsible use of AI.
`.trim();
  }

  return question;
}


function cleanGeneratedAnswer(answer, maxSourceId) {
  let cleaned = answer || "";

  // Remove citation numbers that do not match
  // the sources actually returned.
  cleaned = cleaned.replace(
    /\[(\d+)\]/g,
    (match, number) => {
      const id = Number(number);

      if (id >= 1 && id <= maxSourceId) {
        return `[${id}]`;
      }

      return "";
    }
  );

  // Remove any extra Sources section generated by the model.
  // The frontend already shows the official sources separately.
  cleaned = cleaned.replace(
    /\n\s*Sources?:[\s\S]*$/i,
    ""
  );

  // Convert Markdown links to just their readable label.
cleaned = cleaned.replace(
  /\[([^\]]+)\]\(https?:\/\/[^)]+\)/g,
  "$1"
);

// Remove any raw URLs.
// The frontend displays official source links separately.
cleaned = cleaned.replace(
  /https?:\/\/\S+/g,
  ""
);

// Remove Markdown bold markers.
cleaned = cleaned.replace(
  /\*\*/g,
  ""
);

// Remove lines left containing only citation numbers.
cleaned = cleaned.replace(
  /^\s*(?:\[\d+\]\s*)+$/gm,
  ""
);

cleaned = cleaned
  .replace(/[ \t]+\n/g, "\n")
  .replace(/\n{3,}/g, "\n\n")
  .trim();

  return cleaned;
}

export const handler = async (event) => {
  try {
    const input =
      typeof event.body === "string"
        ? JSON.parse(event.body)
        : event;

    const question =
      input?.question?.trim();


    if (!question) {
      return {
        statusCode: 400,

        headers: corsHeaders(),

        body: JSON.stringify({
          success: false,
          message: "A question is required.",
        }),
      };
    }
    if (detectLegalAdviceIntent(question)) {
      return {
        statusCode: 200,
    
        headers: corsHeaders(),
    
        body: JSON.stringify({
          success: true,
    
          answer:
            "This question asks for personalised legal judgment, strategy or an assessment of what you should do in your individual situation. ClaimReady is not designed to make that decision for you. You may wish to obtain legal advice from a qualified human adviser. I can still help explain the Small Claims Tribunals process, clarify procedural terms, or show you what official Singapore Courts guidance says.",
    
          sources: [],
    
          boundary: "legal-advice",
        }),
      };
    }



    const retrievalQueryText =
      buildRetrievalQuery(question);
    /*
      STEP 1:
      Retrieve relevant chunks from our
      official Singapore Courts Knowledge Base.
    */
    const retrieveCommand =
      new RetrieveCommand({
        knowledgeBaseId: KB_ID,

        retrievalQuery: {
          text: retrievalQueryText,
        },

        retrievalConfiguration: {
          managedSearchConfiguration: {
            numberOfResults: 5,
          },
        },
      });


    const retrieveResponse =
      await knowledgeBaseClient.send(
        retrieveCommand
      );


    const retrievalResults =
      retrieveResponse.retrievalResults || [];


    if (retrievalResults.length === 0) {
      return {
        statusCode: 200,

        headers: corsHeaders(),

        body: JSON.stringify({
          success: true,

          answer:
            "I couldn't find enough information in the official ClaimReady sources to answer that question reliably.",

          sources: [],
        }),
      };
    }


      /*
    STEP 2:
    Deduplicate retrieved chunks by source document.

    Bedrock may retrieve multiple chunks from the same file.
    We combine those chunks so each official source receives
    only one citation number.
  */
  const sourceMap = new Map();

  for (const result of retrievalResults) {
    const s3Uri =
      result.location
        ?.s3Location
        ?.uri || "";

    const fileName =
      getFileName(s3Uri);

    const url =
      SOURCE_URLS[fileName] || null;

    const key =
      url || fileName;

    if (!sourceMap.has(key)) {
      sourceMap.set(key, {
        name: fileName,
        url,
        s3Uri,
        score: result.score ?? null,
        excerpts: [],
      });
    }

    const source =
      sourceMap.get(key);

    if (result.content?.text) {
      source.excerpts.push(
        result.content.text
      );
    }

    if (
      result.score != null &&
      (
        source.score == null ||
        result.score > source.score
      )
    ) {
      source.score = result.score;
    }
  }

  const sources =
    Array.from(sourceMap.values())
      .map((source, index) => ({
        id: index + 1,
        name: source.name,
        url: source.url,
        s3Uri: source.s3Uri,
        score: source.score,
        excerpt:
          source.excerpts.join("\n\n"),
      }));


    /*
      STEP 3:
      Build grounded context for Nova.
    */
    const context = sources
      .map(
        (source) =>
          `[Source ${source.id}: ${source.name}]
${source.excerpt}`
      )
      .join("\n\n");


    const systemPrompt = `
You are Ask ClaimReady, a responsible procedural guidance assistant
for self-represented persons using the Singapore Small Claims Tribunals.

You must answer using ONLY the official source material retrieved
from the ClaimReady Knowledge Base.

RULES:

- Provide general legal and procedural information only.
- Do NOT give personalised legal advice.
- Do NOT predict whether a claim will succeed or fail.
- Do NOT recommend litigation strategy.
- Do NOT invent rules, deadlines, requirements, cases or facts.
- Do NOT make assumptions about the user's situation.
- If the retrieved sources do not contain enough information,
  clearly say that you could not find enough information in
  the official sources.
- If the question asks for something outside the retrieved material,
  do not answer it from general model knowledge.
- Cite factual statements using [1], [2], etc.
- Citation numbers must correspond to the supplied source numbers.
- Do not create citation numbers for sources that were not supplied.
- Do NOT include Markdown links or raw URLs in the answer.
- Do NOT reproduce links found inside the retrieved source text.
- Refer to sources only using citation numbers such as [1] or [2].
- The application will display clickable official source links separately.
- Keep the answer clear and understandable for a non-lawyer.
- If a matter appears to fall outside the SCT, do not recommend
  another court, tribunal or legal process unless the retrieved
  official sources specifically explain that alternative process.
`;


const userPrompt = `
OFFICIAL RETRIEVED SOURCES

${context}

Use only the official sources above when answering the user's question.
`;


    /*
      STEP 4:
      Generate a grounded answer with Nova Lite.
    */
    const converseCommand =
      new ConverseCommand({
        modelId: MODEL_ID,

        guardrailConfig: {
          guardrailIdentifier:
            GUARDRAIL_ID,
        
          guardrailVersion:
            GUARDRAIL_VERSION,
        
          trace: "enabled",
        },

        system: [
          {
            text: systemPrompt,
          },
        ],

        messages: [
          {
            role: "user",
        
            content: [
              {
                text: userPrompt,
              },
        
              {
                guardContent: {
                  text: {
                    text: question,
        
                    qualifiers: [
                      "guard_content",
                    ],
                  },
                },
              },
            ],
          },
        ],

        inferenceConfig: {
          maxTokens: 800,
          temperature: 0.1,
        },
      });


    const modelResponse =
      await modelClient.send(
        converseCommand
      );


      const rawAnswer =
      modelResponse.output
        ?.message
        ?.content
        ?.map(
          (item) => item.text || ""
        )
        .join("")
        .trim();
    
    const answer =
      cleanGeneratedAnswer(
        rawAnswer,
        sources.length
      );


    if (!answer) {
      throw new Error(
        "Bedrock returned an empty answer."
      );
    }


    /*
      STEP 5:
      Return answer + sources to frontend.
    */
    return {
      statusCode: 200,

      headers: corsHeaders(),

      body: JSON.stringify({
        success: true,
        answer,
        sources,
      }),
    };

  } catch (error) {
    console.error(
      "ClaimReady guidance error:",
      error
    );

    return {
      statusCode: 500,

      headers: corsHeaders(),

      body: JSON.stringify({
        success: false,
        message:
          "Unable to retrieve official guidance.",
        error: error.message,
      }),
    };
  }
};